// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Documentation Utilisateur',
      items: [
        'intro', // Introduction à l'application
        'installation', // Guide d'installation
        {
          type: 'category',
          label: 'Fonctionnalités',
          items: [
            'fonctionnalites/overview', // Vue d'ensemble des fonctionnalités
            'fonctionnalites/scanner',  // Utilisation du scanner
            'fonctionnalites/historique', // Gestion de l'historique
            'fonctionnalites/favoris',  // Favoris
             // Gestion des notifications
          ],
        },
        'resolution-de-problemes', // Résolution de problèmes
        'manuel-utilisation', // Manuel d'utilisation complet
        'faq', // Foire Aux Questions
      ],
    },
 
    {
      type: 'category',
      label: 'Documentation Technique',
      items: [
        'doc-technique/intro-technique',
        'doc-technique/product-requirements',
        // 'doc-technique/details-techniques','sproduct-requirements', // Exigences produit
            'doc-technique/ux-design', // Design UX
            'doc-technique/software-architecture', // Architecture logicielle
            'doc-technique/technical-design', // Conception technique
            
            'doc-technique/quality-assurance', // Assurance qualité
            'doc-technique/api', // Documentation API
        'doc-technique/code-source',
      ],
    },
  ],
};

export default sidebars;
